# NumPy

#### Abbreviation for further use

In [1]:
import numpy as np      


###  .array()--->Used to convert into a ndarray object
#### Type casts all to the biggest data type

In [2]:
m=(23+2j,-4)
a=np.array(m)    
a

array([23.+2.j, -4.+0.j])

# Creation of Ndarray
### empty is used to create array with garbage values


In [6]:
a=np.empty([5,4],dtype=int)              #dtype can also be np.int4                                       
b=np.empty([5,4],dtype=int)              

array([[3801156, 6357084, 6357102, 7274595],
       [6553710, 6029409, 6881356, 7471202],
       [7471201, 6029433, 6881378, 6029422],
       [6881388, 6881378, 7602292, 7274606],
       [6881396, 7929958, 6553646, 7077996]])

### zeros and ones 

In [3]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [8]:
np.ones([3,3],dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

## We can also provide custom dtype, its used to get tailor made size of our array

In [4]:
a=np.zeros((2,2),dtype=[('x','i4'),('y','i4')])       #array with custom dtype
a

array([[(0, 0), (0, 0)],
       [(0, 0), (0, 0)]], dtype=[('x', '<i4'), ('y', '<i4')])

### Asarray----->same as array,only asarray has less parameters!!!!!!!!!!!

In [5]:
x=[1,2,3]
z=np.asarray(x)
z
y=np.array(x)
print(y)
print(y.dtype)            
y

[1 2 3]
int32


array([1, 2, 3])

## dtype is not for set and dict

In [6]:
x={1,2,3}
z=np.asarray(x)
z
y=np.array(x)    
y

array({1, 2, 3}, dtype=object)

In [9]:
x={1:"a",2:"b",3:"c"}
z=np.asarray(x)
print(z)
y=np.array(x)
print(y)     
y.dtype                    #both are same only asarray has less parameters!!!!!!!!!!!

{1: 'a', 2: 'b', 3: 'c'}
{1: 'a', 2: 'b', 3: 'c'}


dtype('O')

#### In case of frombffer, b is byte type

In [7]:
s=b"hi"
a=np.frombuffer(s,dtype='S1')   
a                           

array([b'h', b'i'], dtype='|S1')

### The fromiter() function is used to create a new 1-dimensional array from an iterable object

In [9]:
l=[3,4,56,7,1,1,1]
x=np.fromiter(l,dtype=int)      
print(x)
l=range(5)
l=iter(l)

[ 3  4 56  7  1  1  1]


### arange is used to generate a range of numbers in for an array object

In [10]:
np.arange(3,12,2)+2

array([ 5,  7,  9, 11, 13])

### linspace is used to generate an array of equally spaced numbers between a range

In [75]:
np.linspace(2,4,5) #[start,end,number of elements]

array([2. , 2.5, 3. , 3.5, 4. ])

## Parameters of linspace
#### when endpoint = False endpoint not included,Default=True
#### when retstep=True, returns Tuple of ndarray and difference between arrays else linspace returns ndarray,default=false

In [11]:
np.linspace(2,4,5,endpoint=False) 

array([2. , 2.4, 2.8, 3.2, 3.6])

In [21]:
a=np.linspace(2,4,5,retstep=True) 
print(a,type(a))  

(array([2. , 2.5, 3. , 3.5, 4. ]), 0.5) <class 'tuple'>


## logspace- like linspace, but return logarithmic values of each element
### log 2=100,log 4=10000 base and all can be changed  

In [22]:
a=np.logspace(2,4,4).reshape((2,2))
print(a)   

[[  100.           464.15888336]
 [ 2154.43469003 10000.        ]]


# Random
### Numpy also has lots of ways to create random number arrays:

## rand
#### Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1)

## randn
#### Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform

## randint
#### Return random integers from low (inclusive) to high (exclusive).

In [14]:
np.random.rand(2)

array([0.61188108, 0.37566978])

In [15]:
np.random.rand(5,5)

array([[0.20799874, 0.4308294 , 0.66424845, 0.50953521, 0.15011331],
       [0.39101065, 0.81853442, 0.33691394, 0.38527416, 0.05267732],
       [0.5661014 , 0.17044473, 0.26024374, 0.13720901, 0.62464533],
       [0.75908163, 0.29599975, 0.53687503, 0.96443854, 0.58754517],
       [0.25427718, 0.04049051, 0.24372453, 0.07117148, 0.52511922]])

In [17]:
np.random.randn(2)

array([0.76263955, 1.31869997])

In [18]:
np.random.randn(5,5)

array([[ 0.43740397, -2.20777545,  0.4351198 , -1.72505406, -0.25246023],
       [-0.29658957, -1.08541428, -2.72960457,  0.88864604, -0.11758801],
       [ 0.34511704, -1.58145798,  0.98387267,  0.01830587,  0.0029041 ],
       [ 1.19172012,  0.22535727,  0.13657004,  0.80543434,  0.07893826],
       [ 0.92743754,  0.71079345, -1.49568525,  0.55883067,  0.50663372]])

In [19]:
np.random.randint(1,100)

56

In [20]:
np.random.randint(1,100,(10,10))

array([[18, 79, 99, 74, 51, 14, 75, 20, 92, 59],
       [69, 27, 18, 84, 61, 66, 49,  8, 89, 55],
       [46, 75, 25, 63, 16, 69, 25,  1, 53, 53],
       [35, 80, 44, 27, 39, 90, 23, 46, 34, 67],
       [81, 65,  4, 30, 88, 90, 18,  8, 12, 59],
       [91, 13, 27, 57, 53,  6,  9, 50,  5, 47],
       [97, 22, 18, 91, 53, 83, 40, 15, 79, 48],
       [96, 25, 96, 32, 67, 43, 53, 55, 51, 27],
       [94, 83,  8, 66, 48, 66, 49, 35, 97, 76],
       [82, 77, 63,  2, 92, 35, 63, 70, 93, 78]])

# Reshaping

In [46]:
a=np.linspace(2,4,4).reshape((2,2))       #linearly spaced arrays
print(a,type(a))

[[2.         2.66666667]
 [3.33333333 4.        ]] <class 'numpy.ndarray'>


# Flattening ----> used to create a 1-d array of any given array

In [50]:
arr

array([[ 1,  4,  2],
       [ 3,  4,  6],
       [ 0, -1,  5]])

In [51]:
arr.flatten()

array([ 1,  4,  2,  3,  4,  6,  0, -1,  5])

# Indexing/Slicing

In [95]:
a=np.arange(6).reshape((3,2))
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [99]:
print(a[:2,0:1])

[[0]
 [2]]


# slice returns an object with [start,stop,step]

In [24]:
s=slice(2,7,2)
print(s)
a=np.arange(10)
print(a,a[s])

slice(2, 7, 2)
[0 1 2 3 4 5 6 7 8 9] [2 4 6]


In [26]:
a=np.arange(9).reshape((3,3))
print(a,"\n\n",a[0:,1])

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

 [1 4 7]


###  ... means omit that part

In [27]:
print(a[...,1]) 

[1 4 7]


In [118]:
print(a[1,...])

[3 4 5]


In [119]:
print(a[1:,...])

[[3 4 5]
 [6 7 8]]


##  consecutives elements of both list are list to take elements from matrix...eg-->x[0][0] is 1

In [30]:
x=np.array([[1,2],[3,4],[5,6]])
y=x[[0,1,2],[0,1,0]] 
print(x,"\n\n",y)

[[1 2]
 [3 4]
 [5 6]] 

 [1 4 5]


In [31]:
x=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print(x)
r=np.array([[0,0],[3,3]])
print("\n",r)
c=np.array([[0,2],[0,2]])
print("\n",c)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

 [[0 0]
 [3 3]]

 [[0 2]
 [0 2]]


In [32]:
y=x[r,c]
y

array([[ 0,  2],
       [ 9, 11]])

In [33]:
z=x[1:4,1:3]
z

array([[ 4,  5],
       [ 7,  8],
       [10, 11]])

In [34]:
y=x[1:4,[1,2]]   #in prev we had [1:3] which is same as [1,2]
y

array([[ 4,  5],
       [ 7,  8],
       [10, 11]])

### bool indexing is possible

In [35]:
x[x>5] 

array([ 6,  7,  8,  9, 10, 11])

In [148]:
a=np.array([np.nan,1,2,np.nan,3,4,5])
print(a)
print(a[~np.isnan(a)]) #without tilde it will return terms with nan

[nan  1.  2. nan  3.  4.  5.]
[1. 2. 3. 4. 5.]


In [47]:
a=np.array([1,2+1j,2+9j])
print(a[np.iscomplex(a)])
print(a[~np.iscomplex(a)])       #complex form is returned as it is type casted at time of initialization

[2.+1.j 2.+9.j]
[1.+0.j]


### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [49]:
arr=np.array([1,2,1,34,121,21])
print(arr.max())
print(arr.min())
print(arr.argmin())
print(arr.argmax())

121
1
0
4


# Broadcasting


In [18]:
a=np.array([0,1,2,3,4,5]).reshape((3,2))   #or use it as a=np.array([[0,1],[2,3],[4,5]])
b=np.array([10,20,30]).reshape((3,1))
c=a+b
print(a,"\n\n",b,"\n\n",c)


[[0 1]
 [2 3]
 [4 5]] 

 [[10]
 [20]
 [30]] 

 [[10 11]
 [22 23]
 [34 35]]


(3, 2)

In [37]:
a=np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]])
b=np.array([1.0,2.0,3.0])
c=a+b
print(a,"\n\n",b,"\n\n",c)

[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]] 

 [1. 2. 3.] 

 [[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [38]:
for x in a:
    print(x,end=" ")
print("\nnditer() print each element of each row")
for x in np.nditer(a):
    print(x,end=" ")

[0. 0. 0.] [10. 10. 10.] [20. 20. 20.] [30. 30. 30.] 
nditer() print each element of each row
0.0 0.0 0.0 10.0 10.0 10.0 20.0 20.0 20.0 30.0 30.0 30.0 

## transpose
## it will still iter from same location

In [39]:

b=a.T           
print(a,"\n \n after T\n\n",b,"\n\n")
for x in np.nditer(a):
    print(x,end=" ") #here even after T, the value of x dosent change as its still same in memory

[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]] 
 
 after T

 [[ 0. 10. 20. 30.]
 [ 0. 10. 20. 30.]
 [ 0. 10. 20. 30.]] 


0.0 0.0 0.0 10.0 10.0 10.0 20.0 20.0 20.0 30.0 30.0 30.0 

## order is used to specify if it is to be copied c wise(row) or f wise(column)

In [40]:
c=b.copy(order='C')       #c=row
print(c)
for x in np.nditer(c):
    print(x,end=" ")    #here order is changed, as we copied row wise

[[ 0. 10. 20. 30.]
 [ 0. 10. 20. 30.]
 [ 0. 10. 20. 30.]]
0.0 10.0 20.0 30.0 0.0 10.0 20.0 30.0 0.0 10.0 20.0 30.0 

In [43]:
id(a)

1807073275776

In [44]:
id(b)

1807073266064

In [46]:
d=b.copy(order='F')       #f=column
print(d)
for x in np.nditer(d):
    print(x,end=" ")      #here again order is restored as wwe copied column wise

[[ 0. 10. 20. 30.]
 [ 0. 10. 20. 30.]
 [ 0. 10. 20. 30.]]
0.0 0.0 0.0 10.0 10.0 10.0 20.0 20.0 20.0 30.0 30.0 30.0 

# op_flags---->used to give permission to change,default=readonly

In [43]:
for x in np.nditer(a):
    x[...]=2*x
print(a)    #error cause op_flags is [readonly] by default

ValueError: assignment destination is read-only

In [44]:
for x in np.nditer(a,op_flags=['readwrite']):
    x[...]=2*x
print(a)     #error gone as ['readwrite'] is the flag   

[[  0.   0.   0.]
 [ 40.  40.  40.]
 [ 80.  80.  80.]
 [120. 120. 120.]]


In [54]:
for x in np.nditer(a,op_flags=['writeonly']):
    x[...]=2*x
    print(x)                #its reading why? *find its use ----------> it says litreal meaning,reason for ambiguity not found
print(a) 

0.0
0.0
0.0
320.0
320.0
320.0
640.0
640.0
640.0
960.0
960.0
960.0
[[  0.   0.   0.]
 [320. 320. 320.]
 [640. 640. 640.]
 [960. 960. 960.]]


In [3]:
a=[[1,2,3,4],[5,6,7,8]]
b=[0,1,2,3]
for x,y in np.nditer([a,b]):
    print("%d:%d" %(x,y),end=" ")


1:0 2:1 3:2 4:3 5:0 6:1 7:2 8:3 

## code to print contents in new line--->if statement implementation

In [46]:

a=np.array([[1,2,3,4],[5,6,7,8]])
b=np.array([0,1,2,3])
i=1
s,c=a.shape
for x,y in np.nditer([a,b]):
    print("%d:%d" %(x,y),end=" ")
    if i==c:
        i=0
        print()
    i+=1

1:0 2:1 3:2 4:3 
5:0 6:1 7:2 8:3 


# Linear Algebra
#### --->linalg.solve()
#### --->linalg.matrix_rank()
#### --->linalg.power()
#### --->linalg.det()
#### --->linalg.inv()

In [4]:
# coefficients
a = np.array([[1, 2], [3, 4]])
# constants
b = np.array([8, 18])

np.linalg.solve(a, b)

array([2., 3.])

In [5]:
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])

In [8]:
np.linalg.matrix_rank(A)

3

In [10]:
np.linalg.matrix_power(A,3)

array([[336, 162, 228],
       [406, 162, 469],
       [698, 702, 905]])

In [11]:
np.linalg.det(A)

-306.0

In [12]:
np.linalg.inv(A)

array([[ 0.17647059, -0.00326797, -0.02287582],
       [ 0.05882353, -0.13071895,  0.08496732],
       [-0.11764706,  0.1503268 ,  0.05228758]])

# Stacking
Several arrays can be stacked together along different axes.

- **np.vstack:** To stack arrays along vertical axis.

- **np.hstack:** To stack arrays along horizontal axis.

- **np.column_stack:** To stack 1-D arrays as columns into 2-D arrays.

- **np.row_stack:** To stack 1-D arrays as rows into 2-D arrays.

- **np.concatenate:** To stack arrays along specified axis (axis is passed as argument).

In [51]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

In [52]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [53]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [54]:
np.concatenate((a,b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [55]:
np.concatenate((a,b), axis=0) #same as vstack

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

# Splitting

For splitting, we have these fuctions:

- **np.hsplit:** Split array along horizontal axis.

- **np.vsplit:** Split array along vertical axis.

- **np.array_split:** Split array along specified axis.

In [56]:
c=np.array([0,0])
np.row_stack((a,c))   #used to add a 1-d array to a 2-d one

array([[1, 2],
       [3, 4],
       [0, 0]])

In [29]:
a = np.array([[1, 3, 5, 7, 9, 11],
              [2, 4, 6, 8, 10, 12]])

In [31]:
np.hsplit(a,3) #used to split array into to equal parts horizonally

[array([[1, 3],
        [2, 4]]), array([[5, 7],
        [6, 8]]), array([[ 9, 11],
        [10, 12]])]

In [26]:
np.vsplit(a,2) #used to split an array to equal parts vertically

[array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]

In [34]:
np.array_split( a , 2, axis=0) #same as vsplit

[array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]

In [36]:
np.array_split( a , 3, axis=1)  #same as hsplit

[array([[1, 3],
        [2, 4]]), array([[5, 7],
        [6, 8]]), array([[ 9, 11],
        [10, 12]])]

In [39]:
np.array_split( a , 2, axis=0) #used to sort vertically 

[array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]

In [38]:
np.array_split( a , 2, axis=1)

[array([[1, 3, 5],
        [2, 4, 6]]), array([[ 7,  9, 11],
        [ 8, 10, 12]])]

# Sorting

In [26]:
arr = np.array([[1, 4, 2],
                [3, 4, 6],
                [0, -1, 5]])

In [27]:
print(arr)

[[ 1  4  2]
 [ 3  4  6]
 [ 0 -1  5]]


# axis=1,used to sort row wise

In [28]:
np.sort(arr, axis=1) 

array([[ 1,  2,  4],
       [ 3,  4,  6],
       [-1,  0,  5]])

# axis=0,used to sort colmn wise

In [43]:
np.sort(arr, axis=0) 

array([[ 0, -1,  2],
       [ 1,  4,  5],
       [ 3,  4,  6]])

# used to give flatten version sorted array

In [45]:
np.sort(arr, axis=None) 

array([-1,  0,  1,  2,  3,  4,  4,  5,  6])

# Date Time in Numpy

# creating a date----> YYYY-MM-DD

In [14]:

today = np.datetime64('2019-12-05')

In [15]:
today

numpy.datetime64('2019-12-05')

# get year in numpy datetime object

In [16]:

np.datetime64(today, 'Y')

numpy.datetime64('2019')

# creating array of dates in a month

In [17]:

dates = np.arange('2019-01', '2020-02', dtype='datetime64[M]')

In [18]:
dates

array(['2019-01', '2019-02', '2019-03', '2019-04', '2019-05', '2019-06',
       '2019-07', '2019-08', '2019-09', '2019-10', '2019-11', '2019-12',
       '2020-01'], dtype='datetime64[M]')

# arithmetic operation on dates

In [19]:

dur = np.datetime64('2018-07-22') - np.datetime64('2017-05-22')

In [20]:
dur

numpy.timedelta64(426,'D')

# duration in weeks

In [23]:

np.timedelta64(dur, 'W')

numpy.timedelta64(60,'W')

In [24]:
# sorting dates
a = np.array(['2017-02-12', '2016-10-13', '2019-05-22'], dtype='datetime64')
sorted(a)

[numpy.datetime64('2016-10-13'),
 numpy.datetime64('2017-02-12'),
 numpy.datetime64('2019-05-22')]

# Saving an array
## An array can be saved as an .npy(single array) or as an .npz format(Multiple arrays) using Numpy.
### It can be later copied into another sysytem with the same dtype.

In [4]:
a = np.array([[1,2,3],
             [4,5,6]])

b = np.array([[6,5,4],
              [3,2,1]])

## save()---->used to save a single array

In [5]:
np.save("a.npy", a) 

# load()---> used to load the array form .npy file or .npz file


In [6]:
a = np.load("a.npy") 

In [7]:
print(a)

[[1 2 3]
 [4 5 6]]


# savez()---->saving multiple arrays in a file with custom names.

In [8]:
np.savez("AB.npz", x=a, y=b) 

In [9]:
arr = np.load("AB.npz")

### displaying the arrays with their respective custom names

In [10]:
arr['x']

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
arr['y']

array([[6, 5, 4],
       [3, 2, 1]])

In [3]:
a=np.array([[1,2],[3,4]])

In [8]:
a.shape

(2, 2)